name: sf_env
channels:
  - snowflake
dependencies:
  - python=3.8.*
  - sentence-transformers=2.2.2
  - snowflake-ml-python = 1.6.4
  - snowflake-snowpark-python=1.20.0
  - streamlit=1.35.0
  - python-docx=1.1.0
  - python-pptx=0.6.23
  - openpyxl=3.1.5
  - streamlit-extras=0.4.0
