name: sf_env
channels:
  - snowflake
dependencies:
  - faiss-cpu=1.7.4
  - fpdf=1.7.2
  - markdown2=2.4.0
  - python=3.8.*
  - sentence-transformers=2.2.2
  - unidecode=1.2.0
  - snowflake-snowpark-python=1.20.0
  - streamlit=1.35.0
  - python-docx=1.1.0
  - python-pptx=0.6.23
  - openpyxl=3.1.5
  - streamlit-extras=0.4.0
