name: Deploy Streamlit App to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Streamlit tests
      - name: Run Streamlit tests
        run: |
          streamlit run test_app.py --headless

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 6: Format Terraform code
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # Step 7: Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Step 8: Validate Terraform code
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Step 9: Apply Terraform configuration
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
