name: Deploy to Prod

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install snowcli and pytest environment'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-cli-labs
        # Check if snowflake-cli was installed successfully and it's available
        which snowflake-cli
        snowflake-cli --version

    - name: 'Create config'
      shell: bash
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWCLI_PW }}
      run: |
        mkdir -p ~/.snowflake
        cp config.toml ~/.snowflake/config.toml
        echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
        chmod 0600 ~/.snowflake/config.toml

    - name: Test Snowflake Connection
      shell: bash
      run: |
        snowflake-cli "SELECT CURRENT_USER();"
      continue-on-error: false

    - name: 'Deploy the Streamlit app'
      shell: bash
      run: |
        snow streamlit deploy --replace
